Updating README to include more info on plugins
AgnostiqHQ/covalent-aws-plugins pull request #15
Opened 2022-10-04 23:32 UTC by AlejandroEsquivel

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-10-06 21:04 UTC, FyzHsn requested changes
Left two minor revision comments. Otherwise, LGTM!

2022-10-06 21:04 UTC, FyzHsn commented on README.md
> +|![AWS EC2](./doc/static/EC2.png)|AWS EC2 Executor|**General purpose compute workloads users can select compute resources.** An EC2 instance is auto-provisioned using terraform with selected compute
```suggestion
|![AWS EC2](./doc/static/EC2.png)|AWS EC2 Executor|**General purpose compute workloads where users can select compute resources.** An EC2 instance is auto-provisioned using terraform with selected compute settings to execute tasks.|
```

2022-10-06 22:04 UTC, AlejandroEsquivel commented on README.md
> +To use this plugin with Covalent, simply install it with `pip`:
For sure, will change 👍🏼

2022-10-06 22:04 UTC, AlejandroEsquivel commented on README.md
> +|![AWS EC2](./doc/static/EC2.png)|AWS EC2 Executor|**General purpose compute workloads users can select compute resources.** An EC2 instance is auto-provisioned using terraform with selected compute
Nice catch @FyzHsn will fix

2022-10-07 01:51 UTC, FyzHsn requested changes

2022-10-07 01:51 UTC, FyzHsn commented on README.md
> +While each plugin can be seperately installed installing the above pip package installs all of the below plugins.
```suggestion
While each plugin can be installed separately, `covalent-aws-plugins` pip package will automatically download all of the plugins listed below.
```

2022-10-07 22:36 UTC, merged