Modify the execution script to transfer outputs and exceptions via S3
AgnostiqHQ/covalent-aws-plugins pull request #44
Opened 2023-08-31 00:18 UTC by araghukas

Related PR for AWSBatch Executor: [link PR]

Modifies the `exec.py` script to:

- "tee" stdout/stderr to local files
- transfer stdout/stderr and error info via s3 (downloaded and used by plugins)

Note, this preserves the output in CloudWatch logs.

- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-08-31 14:58 UTC, cjao requested changes
This is excellent work. The `_TeeStream` Just few minor adjustments requested.

2023-08-31 14:58 UTC, cjao commented on covalent_aws_plugins/exec.py
> +output_filename = result_filename.replace("result", "output")
Could "output" be renamed to something slightly less ambiguous, such as `io_output`?

2023-08-31 14:58 UTC, cjao commented on covalent_aws_plugins/exec.py
> +local_outputs_filename = os.path.join("/covalent", output_filename)
Same comment here

2023-08-31 14:58 UTC, cjao commented on covalent_aws_plugins/exec.py
> +    pickle.dump((stdout, stderr, traceback_str, exception_cls), f)
Since `exception_cls` is an object generated by the user's code, it might not be unpicklable by the Covalent server which cannot anticipate the object's package dependencies. Consider passing `str(exception_cls)` instead.

More generally, we want to minimize the use of pickle for serializing data between user-controlled environments (such as the SDK and executors) and the Covalent server. Once you've replaced `exception_cls` by its string representation, you can serialize the IO outputs using JSON.

2023-08-31 14:58 UTC, cjao commented on covalent_aws_plugins/exec.py
> +        stdout_tee.streams[1].close()
Implement `close` as a public method of `_TeeStream` to avoid leaking implementation details like the fact that the the auxiliary streams are stored starting from array position 1.

2023-08-31 18:45 UTC, araghukas commented
Hey @cjao, the latest commits should cover the suggested changes. Using JSON now for the io outputs data. I have also pushed matching changes (to digest the JSON, not pickle) to the AWSBatch PR: https://github.com/AgnostiqHQ/covalent-awsbatch-plugin/pull/79

2023-09-01 13:43 UTC, cjao approved these changes
Thanks @araghukas

2023-09-01 13:45 UTC, cjao requested changes
This PR looks good but is just missing a bit of test coverage.

2023-09-01 13:45 UTC, cjao commented on CHANGELOG.md
> +### Changed
Changelog edits should go under the `[UNRELEASED]` block

2023-09-01 13:53 UTC, araghukas commented on CHANGELOG.md
> +### Changed
oops. fixed.

2023-09-01 13:56 UTC, araghukas commented
> This PR looks good but is just missing a bit of test coverage.

@cjao I'll look into this later today :)

2023-09-01 22:30 UTC, araghukas commented
@cjao looks like the coverage issues are due to `exec.py`, which is considerably bigger. Do we expect this file to be covered?

2023-09-29 18:04 UTC, merged